"""init_mailer_schema

Revision ID: a36227e3411a
Revises: 
Create Date: 2026-05-23 07:12:29.796008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a36227e3411a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('secret_ref', sa.String(length=120), nullable=True),
    sa.Column('last_test_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_ok', sa.Boolean(), nullable=True),
    sa.Column('last_test_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'kind', name='uq_channel_company_kind')
    )
    op.create_index(op.f('ix_channel_company_id'), 'channel', ['company_id'], unique=False)
    op.create_table('event_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('source_module', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('source_module', sa.String(length=60), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('to_address', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('dedup_key', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_channel_id'), 'message', ['channel_id'], unique=False)
    op.create_index(op.f('ix_message_company_id'), 'message', ['company_id'], unique=False)
    op.create_index(op.f('ix_message_created_at'), 'message', ['created_at'], unique=False)
    op.create_index(op.f('ix_message_dedup_key'), 'message', ['dedup_key'], unique=False)
    op.create_index('ix_message_status_created', 'message', ['status', 'created_at'], unique=False)
    op.create_table('poll_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('last_update_id', sa.BigInteger(), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    op.create_table('routing_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('event_type_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routing_rule_channel_id'), 'routing_rule', ['channel_id'], unique=False)
    op.create_index(op.f('ix_routing_rule_company_id'), 'routing_rule', ['company_id'], unique=False)
    op.create_index(op.f('ix_routing_rule_event_type_id'), 'routing_rule', ['event_type_id'], unique=False)
    op.create_table('telegram_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('chat_type', sa.String(length=20), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('is_member', sa.Boolean(), nullable=False),
    sa.Column('can_send', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'chat_id', name='uq_telegram_group_company_chat')
    )
    op.create_index(op.f('ix_telegram_group_branch_id'), 'telegram_group', ['branch_id'], unique=False)
    op.create_index(op.f('ix_telegram_group_channel_id'), 'telegram_group', ['channel_id'], unique=False)
    op.create_index(op.f('ix_telegram_group_company_id'), 'telegram_group', ['company_id'], unique=False)
    op.create_table('inbound_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('from_user_id', sa.BigInteger(), nullable=True),
    sa.Column('from_username', sa.String(length=120), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_update_id', sa.BigInteger(), nullable=False),
    sa.Column('reply_to_telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('reply_to_message_id', sa.Integer(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_message_id'], ['message.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'telegram_update_id', name='uq_inbound_channel_update')
    )
    op.create_index(op.f('ix_inbound_message_channel_id'), 'inbound_message', ['channel_id'], unique=False)
    op.create_index(op.f('ix_inbound_message_chat_id'), 'inbound_message', ['chat_id'], unique=False)
    op.create_index(op.f('ix_inbound_message_company_id'), 'inbound_message', ['company_id'], unique=False)
    op.create_index(op.f('ix_inbound_message_created_at'), 'inbound_message', ['created_at'], unique=False)
    op.create_index(op.f('ix_inbound_message_reply_to_message_id'), 'inbound_message', ['reply_to_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inbound_message_reply_to_message_id'), table_name='inbound_message')
    op.drop_index(op.f('ix_inbound_message_created_at'), table_name='inbound_message')
    op.drop_index(op.f('ix_inbound_message_company_id'), table_name='inbound_message')
    op.drop_index(op.f('ix_inbound_message_chat_id'), table_name='inbound_message')
    op.drop_index(op.f('ix_inbound_message_channel_id'), table_name='inbound_message')
    op.drop_table('inbound_message')
    op.drop_index(op.f('ix_telegram_group_company_id'), table_name='telegram_group')
    op.drop_index(op.f('ix_telegram_group_channel_id'), table_name='telegram_group')
    op.drop_index(op.f('ix_telegram_group_branch_id'), table_name='telegram_group')
    op.drop_table('telegram_group')
    op.drop_index(op.f('ix_routing_rule_event_type_id'), table_name='routing_rule')
    op.drop_index(op.f('ix_routing_rule_company_id'), table_name='routing_rule')
    op.drop_index(op.f('ix_routing_rule_channel_id'), table_name='routing_rule')
    op.drop_table('routing_rule')
    op.drop_table('poll_state')
    op.drop_index('ix_message_status_created', table_name='message')
    op.drop_index(op.f('ix_message_dedup_key'), table_name='message')
    op.drop_index(op.f('ix_message_created_at'), table_name='message')
    op.drop_index(op.f('ix_message_company_id'), table_name='message')
    op.drop_index(op.f('ix_message_channel_id'), table_name='message')
    op.drop_table('message')
    op.drop_table('event_type')
    op.drop_index(op.f('ix_channel_company_id'), table_name='channel')
    op.drop_table('channel')
    # ### end Alembic commands ###
